### Register user
POST http://localhost:3333/api/v1/register
Content-Type: application/json

{
    "firstName": "Caio",
    "lastName": "Fernando",
    "email": "email@email.com",
    "password": "123456"
}

### Login user
POST http://localhost:3333/api/v1/login
Content-Type: application/json

{
    "email": "email@email.com",
    "password": "123456"
}

### List products
GET http://localhost:3333/api/v1/products

### Create product
POST http://localhost:3333/api/v1/products
Content-Type: application/json

{
    "name": "Nome",
    "description": "Descrição",
    "quantity": 20,
    "price": 19.99,
    "image": "image.png"
}

### Create cart checkout
POST http://localhost:3333/api/v1/cart/checkout
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkQXQiOjE3MTM1NjI5NjEsInVzZXJJRCI6IjEifQ.Cw36CHko4Zo8umTHLhu6MTeKtrvBV3X82d67JJbyLdw

{
    "items": [
        {
            "productID": 1,
            "quantity": 1
        }
    ]
}
